# Generated by Django 4.0.1 on 2022-01-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchCode', models.CharField(max_length=20)),
                ('OriginalCipherFromDocument', models.CharField(max_length=128)),
                ('Name', models.CharField(max_length=255)),
                ('Unit', models.CharField(max_length=64)),
            ],
        ),
    ]
