# Generated by Django 4.0.1 on 2022-01-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIBase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='OriginalCipherFromDocument',
            new_name='originalCipherFromDocument',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='SearchCode',
            new_name='searchCode',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='Unit',
            new_name='unit',
        ),
    ]
