# Generated by Django 4.0.1 on 2022-01-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIBase', '0005_alter_resourcerequirement_consumptionrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Единица измерения')),
                ('denominator', models.IntegerField(verbose_name='Делитель')),
            ],
        ),
        migrations.RemoveField(
            model_name='standard',
            name='Resources',
        ),
        migrations.AlterField(
            model_name='resources',
            name='code',
            field=models.IntegerField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APIBase.unit'),
        ),
    ]
