# Generated by Django 4.0.1 on 2022-01-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIBase', '0007_resourcerequirement_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequirement',
            name='consumptionRate',
            field=models.FloatField(verbose_name='Норма расхода '),
        ),
    ]
